imports:
  - { resource: 'routes/*.yaml', type: glob }
rootPageId: 3
base: /
languages:
  -
    title: Deutsch
    enabled: true
    languageId: 0
    base: /
    typo3Language: default
    locale: de_DE.UTF-8
    iso-639-1: de
    navigationTitle: Deutsch
    hreflang: de-de
    direction: ltr
    flag: de
errorHandling:
  -
    errorCode: 404
    errorHandler: Page
    errorContentSource: 't3://page?uid=10'
  -
    errorCode: 503
    errorHandler: Fluid
    errorFluidTemplate: 'EXT:crea_theme_child/Resources/Private/Templates/Errors/503/de.html'
    errorFluidTemplatesRootPath: ''
    errorFluidLayoutsRootPath: ''
    errorFluidPartialsRootPath: ''
routes: {  }
websiteTitle: 'New website'
